# Generated by Django 6.0.5 on 2026-06-18 05:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("auctions", "0002_alter_auction_starting_price_bid"),
    ]

    operations = [
        migrations.AddField(
            model_name="bid",
            name="user_email",
            field=models.EmailField(default="my@email.com", max_length=254),
        ),
        migrations.AlterField(
            model_name="auction",
            name="status",
            field=models.CharField(
                choices=[
                    ("active", "Active"),
                    ("ended", "Ended"),
                    ("scheduled", "Scheduled"),
                ],
                default="scheduled",
                max_length=20,
            ),
        ),
    ]
